service: test-backend

useDotenv: true

plugins:
  - serverless-offline
  - serverless-offline-watcher

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY
